export const COUNTRIES = [
  { value: 'Brasil', flag: '🇧🇷' },
  { value: 'Argentina', flag: '🇦🇷' },
  { value: 'Alemanha', flag: '🇩🇪' },
  { value: 'França', flag: '🇫🇷' },
  { value: 'Espanha', flag: '🇪🇸' },
  { value: 'Itália', flag: '🇮🇹' },
  { value: 'Portugal', flag: '🇵🇹' },
  { value: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { value: 'Uruguai', flag: '🇺🇾' },
  { value: 'Colômbia', flag: '🇨🇴' },
  { value: 'Chile', flag: '🇨🇱' },
  { value: 'México', flag: '🇲🇽' },
  { value: 'Estados Unidos', flag: '🇺🇸' },
  { value: 'Japão', flag: '🇯🇵' },
  { value: 'Coreia do Sul', flag: '🇰🇷' },
  { value: 'Holanda', flag: '🇳🇱' },
  { value: 'Bélgica', flag: '🇧🇪' },
  { value: 'Croácia', flag: '🇭🇷' },
  { value: 'Senegal', flag: '🇸🇳' },
  { value: 'Marrocos', flag: '🇲🇦' },
];

export const MOCK_STICKERS = [
  {
    id: '1',
    name: 'shakira',
    age: 28,
    country: 'Brasil',
    flag: '🇧🇷',
    image: 'https://i.pinimg.com/1200x/24/27/5c/24275c17c29ff0b5fe8305f8f2cbe0f1.jpg',
  },
  {
    id: '2',
    name: 'María García',
    age: 25,
    country: 'Argentina',
    flag: '🇦🇷',
    image: 'https://i.pinimg.com/736x/6a/6b/54/6a6b541b86fc15c339ef067e8da5fa83.jpg',
  },
  {
    id: '3',
    name: 'Hans Müller',
    age: 30,
    country: 'Alemanha',
    flag: '🇩🇪',
    image: 'https://portalg.com.br/wp-content/uploads/2026/05/figurinha-copa-gerada-por-ia.webp',
  },
  {
    id: '4',
    name: 'Pierre Dubois',
    age: 27,
    country: 'França',
    flag: '🇫🇷',
    image: 'https://i.pinimg.com/1200x/1a/2f/b2/1a2fb261b6f9e92528bce2439e65ee99.jpg',
  },
  {
    id: '5',
    name: 'Carlos Mendez',
    age: 26,
    country: 'México',
    flag: '🇲🇽',
    image: 'https://i.imgur.com/FubhhcQ.png',
  },
];
